### ISSUE TITLE
Pubdate does not allow for books published < 1 AD

### ISSUE THREAD

**Issue by jd7h** [jd7h/josephine#58]
Problem arose when importing GoodReads books that included Chinese/Greek classics.

**Comment by jd7h** [comment]
Books that triggered this error:
Oeconomicus by Xenophon (362 BC)
Tao Te Ching by Lao Zu (600 BC)

**Comment by jd7h** [comment]
Error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/judith/git/josephine/scripts/goodreads_importer.py", line 92, in main
    goodreads_record_to_book(record)
  File "/home/judith/git/josephine/scripts/goodreads_importer.py", line 32, in goodreads_record_to_book
    book.pubdate = datetime.datetime(year=int(record['Original Publication Year']), day=1, month=1)
ValueError: year -600 is out of range
```
